export const projects = [
  {
    id: '6',
    link: '/portfolio/my-top',
    title: 'My Top',
    description: 'Educational full stack project. Service for rating courses, services, books...',
    year: 2023,
    iconsSrc: ['/icons/icon-typescript.svg', '/icons/icon-next.svg', '/icons/icons-nest.svg', '/icons/icon-mongo.svg'],
  },
  {
    id: '5',
    link: '/portfolio/github-search',
    title: 'Github Seasch',
    description: 'Service for searching repositories on Github by username.',
    year: 2023,
    iconsSrc: [
      '/icons/icon-typescript.svg',
      '/icons/react_icon.svg',
      '/icons/icon-redux.svg',
      '/icons/icon-tailwind.svg',
      '/icons/axios_icon.svg',
    ],
  },
  {
    id: '4',
    link: '/portfolio/blog-me',
    title: 'Blog Me',
    description: 'Educational full stack project. Blog, with the ability to write articles.',
    year: 2023,
    iconsSrc: [
      '/icons/icon-javascript.svg',
      '/icons/react_icon.svg',
      '/icons/icon-redux.svg',
      '/icons/icon-mui.svg',
      '/icons/icon-express.svg',
      '/icons/icon-mongo.svg',
      '/icons/axios_icon.svg',
    ],
  },
  {
    id: '3',
    link: '/portfolio/baths-restoration',
    title: 'Baths restoration',
    description: 'Landing page with semantic, adaptive layout, using tools such as Gulp, Pug, Bootstrap.',
    year: 2023,
    iconsSrc: [
      '/icons/iconhtml.svg',
      '/icons/iconcss.svg',
      '/icons/icon-javascript.svg',
      '/icons/icons-gulp.png',
      '/icons/pug_icon.svg',
      '/icons/icon-bootstrap.svg',
    ],
  },
  {
    id: '2',
    link: '/portfolio/cleanhouse',
    title: 'Clean House',
    description: 'Semantic, valid, adaptive, fluid, cross-browser website layout for the Clean House company.',
    year: 2023,
    iconsSrc: [
      '/icons/iconhtml.svg',
      '/icons/iconcss.svg',
      '/icons/icon-javascript.svg',
      '/icons/iconsass.svg',
      '/icons/icons-gulp.png',
    ],
  },
  {
    id: '1',
    link: '/portfolio/krossover',
    title: 'Krossover',
    description: 'Оn-line store for selling shoes and clothing.',
    year: 2022,
    iconsSrc: ['/icons/iconhtml.svg', '/icons/iconcss.svg', '/icons/icon-wordpress.svg'],
  },
];
