export const projectsRu = [
  {
    id: '8',
    link: '/portfolio/todo',
    title: 'My ToDo List',
    description: 'Фулл стек приложение для составления списка задач.',
    year: 2024,
    iconsSrc: [
      '/icons/icon-typescript.svg',
      '/icons/icon-next.svg',
      '/icons/icons-nest.svg',
      '/icons/icon-mongo.svg',
      '/icons/icon-docker.svg',
    ],
  },
  {
    id: '8',
    link: '/portfolio/spotify-clone',
    title: 'Spotify-Clone',
    description: 'Музыкальная платформа',
    year: 2023,
    iconsSrc: [
      '/icons/icon-typescript.svg',
      '/icons/icon-next.svg',
      '/icons/icons-nest.svg',
      '/icons/icon-mongo.svg',
      '/icons/icon-mui.svg',
    ],
  },
  {
    id: '7',
    link: '/portfolio/live-chat',
    title: 'On-Line Chat',
    description: 'Он-лайн чат',
    year: 2023,
    iconsSrc: [
      '/icons/icon-typescript.svg',
      '/icons/icons-nest.svg',
      '/icons/icon-postgresql.svg',
      '/icons/socket-icon.svg',
    ],
  },
  {
    id: '6',
    link: '/portfolio/my-top',
    title: 'My Top',
    description: 'Учебный фулл стек проект. Сервис для рейтинга курсов, услуг, книг...',
    year: 2023,
    iconsSrc: [
      '/icons/icon-typescript.svg',
      '/icons/icon-next.svg',
      '/icons/icons-nest.svg',
      '/icons/icon-mongo.svg',
      '/icons/icon-docker.svg',
    ],
  },
  {
    id: '5',
    link: '/portfolio/github-search',
    title: 'Github Seasch',
    description: 'Сервис для поиска репозиториев на Github по имени пользователя.',
    year: 2023,
    iconsSrc: [
      '/icons/icon-typescript.svg',
      '/icons/react_icon.svg',
      '/icons/icon-redux.svg',
      '/icons/icon-tailwind.svg',
      '/icons/axios_icon.svg',
    ],
  },
  {
    id: '4',
    link: '/portfolio/blog-me',
    title: 'Blog Me',
    description: 'Учебный фулл стек проект. Блог, с возможностью написания статей.',
    year: 2023,
    iconsSrc: [
      '/icons/icon-javascript.svg',
      '/icons/react_icon.svg',
      '/icons/icon-redux.svg',
      '/icons/icon-mui.svg',
      '/icons/icon-express.svg',
      '/icons/icon-mongo.svg',
      '/icons/axios_icon.svg',
    ],
  },
  {
    id: '3',
    link: '/portfolio/baths-restoration',
    title: 'Baths restoration',
    description:
      'Посадочная страница с семантической, адаптивной версткой, с использованием таких инструментов, как Gulp, Pug, Bootstrap.',
    year: 2023,
    iconsSrc: [
      '/icons/iconhtml.svg',
      '/icons/iconcss.svg',
      '/icons/icon-javascript.svg',
      '/icons/icons-gulp.png',
      '/icons/pug_icon.svg',
      '/icons/icon-bootstrap.svg',
    ],
  },
  {
    id: '2',
    link: '/portfolio/cleanhouse',
    title: 'Clean House',
    description: 'Семантическая, валидная, адаптивная, кроссбраузерная верстка сайта для компании "Чистый дом".',
    year: 2023,
    iconsSrc: [
      '/icons/iconhtml.svg',
      '/icons/iconcss.svg',
      '/icons/icon-javascript.svg',
      '/icons/iconsass.svg',
      '/icons/icons-gulp.png',
    ],
  },
  {
    id: '1',
    link: '/portfolio/krossover',
    title: 'Krossover',
    description: 'Онлайн-магазин по продаже обуви и одежды.',
    year: 2022,
    iconsSrc: ['/icons/iconhtml.svg', '/icons/iconcss.svg', '/icons/icon-wordpress.svg'],
  },
];
